# Generated by Django 4.2.6 on 2023-11-18 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0006_merge_20231117_2225"),
        ("genioapp", "0007_remove_course_categories_remove_course_students_and_more"),
    ]

    operations = []
